# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 19:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-posted', '-score']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-posted']},
        ),
        migrations.AddField(
            model_name='answer',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 24, 19, 37, 6, 800450, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
